"""
Django settings for social_site project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*xkl2jb1#tbr+sqmxy&+zal!c7$j)^g&)c=24^%ay^i1_d25!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'crispy_forms', #app to make prettier forms

    'accounts', #gestisce la registrazione di novi utenti al sito
    'core', #gestisce gli aspetti generali, come la ricerca nel sito
    'forum', #gestisce la parte social, come discussioni e post 

    'betmatcher'
]

#per maggiori informazioni visita il sito ufficilae di crispy forms
CRISPY_TEMPLATE_PACK = "bootstrap4"

# CRISPY_CLASS_CONVERTERS = {'input-group': "input-group input-group-sm", 
#                         'numberinput': 'numberinput input-sm',
#                         'form-control': 'form-control input-sm'
#                         }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',
                BASE_DIR / 'accounts/templates',
                BASE_DIR / 'core/templates',
                BASE_DIR / 'forum/templates',
                BASE_DIR / 'betmatcher/templates',
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

# DATABASE_ROUTERS = ['betmatcher.routers.BetMatcherRouter']


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'it'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

#IMPOSTARE CON LE CREDENZIALI DELL'ACCOUNT CHE SI OCCUPA DI MANDARE LE MAIL DA PARTE DEL SITO
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'django.socialsite.email@gmail.com'
# EMAIL_HOST_PASSWORD = 'gzX*T12qdr.2t3#'
# DEFAULT_FROM_EMAIL = 'django.socialsitesupport@gmail.com>'
# DEFAULT_TO_EMAIL = 'to email'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATICFILES_DIRS = [BASE_DIR / 'static-storage']

STATIC_URL = '/static/'

#media root e media url mi permettono di prendere i file media, come le immagini
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR) , 'media-serve') 

MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = "/"    #link dove andare dopo il login




