# Generated by Django 3.1.7 on 2021-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.TextField(blank=True, null=True)),
                ('tournament', models.TextField(blank=True, null=True)),
                ('betradarid', models.IntegerField(blank=True, db_column='betRadarID', null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('bet', models.TextField(blank=True, null=True)),
                ('betodd', models.FloatField(blank=True, db_column='betOdd', null=True)),
            ],
            options={
                'unique_together': {('bookmaker', 'betradarid', 'event', 'bet')},
            },
        ),
    ]
